lista_colores = ["rojo", "azul", "verde", "amarillo"]
# lista_colores.insert(0,"gris")
# lista_colores.append("rosa")
# lista_colores.insert(-3,"naranja")
# lista_colores.pop(1)
# lista_colores.pop(-3)
# lista_colores.pop(-2)
lista_colorescopy = lista_colores.copy()
print(lista_colores)
print(lista_colorescopy)